### PR TITLE
meson: build the test server when -Ddfuzzer-test-server=true

### PR DESCRIPTION
**Pull request by evverx**
It can't be integrated into the CI yet because it fails to compile
with -Werror: https://github.com/matusmarhefka/dfuzzer/issues/49
and it doesn't seem to be possible to hook it up to the
system bus: https://github.com/matusmarhefka/dfuzzer/pull/48#issuecomment-1110353514

It's useful anyway because on machines where it can
connect to a session bus it can be used to somewhat test dfuzzer
without affecting other DBus services.

Prompted by https://github.com/matusmarhefka/dfuzzer/issues/45#issuecomment-1110191645

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Nice, thanks! I'll look into making it compile with `-Werrror`.

**Comment by evverx** [comment]
FWIW I managed to run the test server in https://github.com/matusmarhefka/dfuzzer/pull/48 and it triggered https://github.com/matusmarhefka/dfuzzer/issues/19 among other things:
```
2022-04-27T05:40:55.4719122Z [SESSION BUS]
2022-04-27T05:40:55.4728227Z Bus not found.
2022-04-27T05:40:55.4728768Z [SYSTEM BUS]
2022-04-27T05:40:55.4767125Z [PROCESS: /usr/bin/dfuzzer-test-server]
2022-04-27T05:40:55.4767879Z [CONNECTED TO PID: 3143]
2022-04-27T05:40:55.4768606Z Object: /
2022-04-27T05:40:55.4787579Z Object: /org
2022-04-27T05:40:55.4803076Z Object: /org/freedesktop
2022-04-27T05:40:55.4817396Z Object: /org/freedesktop/dfuzzerObject
2022-04-27T05:40:55.4837676Z  Interface: org.freedesktop.DBus.Properties
2022-04-27T05:40:55.4928254Z   Get...  PASS Get
2022-04-27T05:40:55.4980173Z   GetAll...  PASS GetAll
2022-04-27T05:40:55.5036445Z   Set...  PASS Set
2022-04-27T05:40:55.5037084Z  Interface: org.freedesktop.DBus.Introspectable
2022-04-27T05:40:55.5051468Z   SKIP Introspect - void method
2022-04-27T05:40:55.5052033Z  Interface: org.freedesktop.DBus.Peer
2022-04-27T05:40:55.5066417Z   SKIP Ping - void method
2022-04-27T05:40:55.5067146Z  Interface: org.freedesktop.dfuzzerInterface
2022-04-27T05:40:55.5068075Z   SKIP GetMachineId - void method
2022-04-27T05:40:55.7108867Z   WARN df_hello - memory usage 3.0x more than initial memory
2022-04-27T05:40:55.7109791Z    (11024 -> 33252 [kB])
2022-04-27T05:40:55.9544646Z   WARN df_hello - memory usage 6.0x more than initial memory
2022-04-27T05:40:55.9545269Z    (11024 -> 66508 [kB])
2022-04-27T05:40:56.3963368Z   WARN df_hello - memory usage 12.1x more than initial memory
2022-04-27T05:40:56.3964130Z    (11024 -> 133032 [kB])
2022-04-27T05:41:04.9395583Z   FAIL df_crash - process exited
2022-04-27T05:41:04.9395957Z    [PID: 3143], [MEM: 249092 kB]
2022-04-27T05:41:04.9396293Z    on input:
2022-04-27T05:41:04.9396868Z     --i-- '-2147483648'
2022-04-27T05:41:04.9397601Z    reproducer: dfuzzer -v -n org.freedesktop.dfuzzerServer -o /org/freedesktop/dfuzzerObject -i org.freedesktop.dfuzzerInterface -t df_crash
2022-04-27T05:41:09.9428022Z Error: Could not get PID of name 'org.freedesktop.dfuzzerServer': no such name.
2022-04-27T05:41:09.9434318Z Exit status: 1
2022-04-27T05:41:09.9860397Z   df_hello...  df_crash...
2022-04-27T05:41:09.9878521Z ##[error]Process completed with exit code 1.
```
I need to also make it dbus activatable though

**Comment by mrc0mmand** [comment]
> FWIW I managed to run the test server in #48 and it triggered #19 among other things:
> 
> ```
> 2022-04-27T05:40:55.4719122Z [SESSION BUS]
> 2022-04-27T05:40:55.4728227Z Bus not found.
> 2022-04-27T05:40:55.4728768Z [SYSTEM BUS]
> 2022-04-27T05:40:55.4767125Z [PROCESS: /usr/bin/dfuzzer-test-server]
> 2022-04-27T05:40:55.4767879Z [CONNECTED TO PID: 3143]
> 2022-04-27T05:40:55.4768606Z Object: /
> 2022-04-27T05:40:55.4787579Z Object: /org
> 2022-04-27T05:40:55.4803076Z Object: /org/freedesktop
> 2022-04-27T05:40:55.4817396Z Object: /org/freedesktop/dfuzzerObject
> 2022-04-27T05:40:55.4837676Z  Interface: org.freedesktop.DBus.Properties
> 2022-04-27T05:40:55.4928254Z   Get...  PASS Get
> 2022-04-27T05:40:55.4980173Z   GetAll...  PASS GetAll
> 2022-04-27T05:40:55.5036445Z   Set...  PASS Set
> 2022-04-27T05:40:55.5037084Z  Interface: org.freedesktop.DBus.Introspectable
> 2022-04-27T05:40:55.5051468Z   SKIP Introspect - void method
> 2022-04-27T05:40:55.5052033Z  Interface: org.freedesktop.DBus.Peer
> 2022-04-27T05:40:55.5066417Z   SKIP Ping - void method
> 2022-04-27T05:40:55.5067146Z  Interface: org.freedesktop.dfuzzerInterface
> 2022-04-27T05:40:55.5068075Z   SKIP GetMachineId - void method
> 2022-04-27T05:40:55.7108867Z   WARN df_hello - memory usage 3.0x more than initial memory
> 2022-04-27T05:40:55.7109791Z    (11024 -> 33252 [kB])
> 2022-04-27T05:40:55.9544646Z   WARN df_hello - memory usage 6.0x more than initial memory
> 2022-04-27T05:40:55.9545269Z    (11024 -> 66508 [kB])
> 2022-04-27T05:40:56.3963368Z   WARN df_hello - memory usage 12.1x more than initial memory
> 2022-04-27T05:40:56.3964130Z    (11024 -> 133032 [kB])
> 2022-04-27T05:41:04.9395583Z   FAIL df_crash - process exited
> 2022-04-27T05:41:04.9395957Z    [PID: 3143], [MEM: 249092 kB]
> 2022-04-27T05:41:04.9396293Z    on input:
> 2022-04-27T05:41:04.9396868Z     --i-- '-2147483648'
> 2022-04-27T05:41:04.9397601Z    reproducer: dfuzzer -v -n org.freedesktop.dfuzzerServer -o /org/freedesktop/dfuzzerObject -i org.freedesktop.dfuzzerInterface -t df_crash
> 2022-04-27T05:41:09.9428022Z Error: Could not get PID of name 'org.freedesktop.dfuzzerServer': no such name.
> 2022-04-27T05:41:09.9434318Z Exit status: 1
> 2022-04-27T05:41:09.9860397Z   df_hello...  df_crash...
> 2022-04-27T05:41:09.9878521Z ##[error]Process completed with exit code 1.
> ```
> 
> I need to also make it dbus activatable though

Making the leak detection optional is definitely the next thing on my TODO list.

**Comment by evverx** [comment]
@mrc0mmand I'm not a fan of that memory leak detector to be honest. I think memory leaks should be detected by LSan, Valgrind and so on. I'd just remove it. That's probably controversial though.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I'm not a fan of that memory leak detector to be honest. I think memory leaks should be detected by LSan, Valgrind and so on. I'd just remove it. That's probably controversial though.

I've played with that idea as well, since it introduces a lot of overhead, both runtime and code-wise, so by dropping it the code would be so. much. simpler.

I can prep a PR with that change to see how it would look/behave once I'm done with the test-server stuff.

**Pull request merged**
