### PR TITLE
ci: turn on Packit

### PR DESCRIPTION
**Pull request by evverx**
to make sure the package is buildable on various architectures.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
@evverx I'll be poking here during the day to see if the permissions got resolved, still can see that "Namespace is not allowed" but in the meantime @mfocko used his magic

**Comment by evverx** [comment]
I'll go ahead and merge it because it can be used to make sure that https://github.com/matusmarhefka/dfuzzer/pull/24 doesn't break the package.

**Pull request merged**
