### PR TITLE
fuzz: avoid leaking memory

### PR DESCRIPTION
**Pull request by mrc0mmand**
Temporary kludge to stop leaking memory while simultaneously not crashing
when the fuzzed app crashes.

This also reverts commit 5e0028f2dde2742cd8b90d94ac1a6569c6718aa0.

Resolves: #45

---

The offending code is in a serious need of refactoring, but until then let's avoid both the memory leak and the crash using a relatively... simple-ish kludge.

### CODE REVIEW

**Comment by evverx** [comment]
@mrc0mmand let's set up the test server first. I've just added the meson glue to build it and managed to crash it with `dfuzzer`:
```sh
$ ./build/dfuzzer -n org.freedesktop.dfuzzerServer
[SESSION BUS]
[PROCESS: /home/vagrant/dfuzzer/build/dfuzzer-test-server]
[CONNECTED TO PID: 94067]
Object: /
Object: /org
Object: /org/freedesktop
Object: /org/freedesktop/dfuzzerObject
 Interface: org.freedesktop.DBus.Properties
 Interface: org.freedesktop.DBus.Introspectable
 Interface: org.freedesktop.DBus.Peer
 Interface: org.freedesktop.dfuzzerInterface
  FAIL df_crash - process exited
   [PID: 94067], [MEM: 6012 kB]
   on input:
    --s [length: 50 B]-- 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    --i-- '2147483647'
   reproducer: dfuzzer -v -n org.freedesktop.dfuzzerServer -o /org/freedesktop/dfuzzerObject -i org.freedesktop.dfuzzerInterface -t df_crash
Error: The connection does not exist.
[SYSTEM BUS]
Error: The connection does not exist.
Couldn't get the PID of the tested process
Exit status: 1
```
The exit status seems to be wrong by the way. It should be 2 I think but that' probably another bug.

**Comment by evverx** [comment]
Looking at https://github.com/matusmarhefka/dfuzzer/pull/48 I think it's going to be a bumpy ride.

**Comment by mrc0mmand** [comment]
Superseded by https://github.com/matusmarhefka/dfuzzer/pull/53.

**Comment by evverx** [comment]
@mrc0mmand I think that PR is somewhat controversial so it should probably be OKed by @matusmarhefka first. While I think the memory leak should be removed it could be that I'm missing something. What I'm trying to say is that maybe in this particular case it would make sense to merge this PR and wait for @matusmarhefka there. WDYT?

**Comment by mrc0mmand** [comment]
> I could rewrite the memory leak fix for the current master (since the fix in #53 is definitely cleaner) and then rebase #53, so we can go forward just with the fix.

Just opened https://github.com/matusmarhefka/dfuzzer/pull/54.

**Pull request closed without merging**
