### PR TITLE
A couple of fixes cherry-picked from #64

### PR DESCRIPTION
**Pull request by mrc0mmand**
As proposed in https://github.com/matusmarhefka/dfuzzer/pull/64#issuecomment-1119219580.

### CODE REVIEW

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

Looking at the coverage report I wasn't sure why `df_noreply` wasn't covered at all and then I found https://github.com/matusmarhefka/dfuzzer/pull/53/files#r862387565 where it was replaced with `df_hang`. Looks like I overlooked that at the time. It can be fixed later though. The PR looks good to me. I'll go ahead and merge it.

**Comment by evverx** [comment]
My bad. It wasn't replaced with `df_hang`. It isn't covered because it isn't called explicitly anywhere and when it's called it crash afterwards.

**Comment by mrc0mmand** [comment]
> My bad. It wasn't replaced with `df_hang`. It isn't covered because it isn't called explicitly anywhere and when it's called `dfuzzer` crashes afterwards.

Yeah, to cover it as well, we'd have to create a custom `abort()` function, which would call `_gcov_flush()` beforehand, but I don't think it's worth the hassle.

**Comment by evverx** [comment]
Agreed. As long as it's actually tested it doesn't matter whether it's included in the coverage report or not. I just got confused for a second :-)

**Pull request merged**
