### PR TITLE
rand: fix a missing dereference

### PR DESCRIPTION
**Pull request by mrc0mmand**
Resolves: CID#257767

### CODE REVIEW

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

**Comment by evverx** [comment]
@mrc0mmand I wonder if anyone figured out why notifications from Coverity Scan seem to vanish into this air?

**Comment by evverx** [comment]
By the way looks like LGTM doesn't fail when `.lgtm.yaml` is intact so it appears it isn't as bad as I thought.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I wonder if anyone figured out why notifications from Coverity Scan seem to vanish into this air?

Unfortunately, no. I can probe this further on Monday. Maybe it would be indeed worthwhile to move this repo under an organization (e.g. dfuzzer/dfuzzer), so the access to the repo secrets is not tied to just a one person, making it a bit more flexible.

**Pull request merged**
