### PR TITLE
fuzz: fix gvariant deconstruction in df_fuzz_write_log()

### PR DESCRIPTION
**Pull request by mrc0mmand**
Resolves: CID#254686

### CODE REVIEW

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

I think in an ideal world `g_variant_get(..., var)` would have failed to compile but because of `...` it slipped in. I'll go ahead and merge it and send it to Coverity shortly.

**Comment by evverx** [comment]
Judging by "Defects eliminated: 2" the backslash made Coverity finally happy as well

**Comment by evverx** [comment]
Turns out clang isn't happy :-)
```sh
FAILED: dfuzzer.p/src_rand.c.o 
clang -Idfuzzer.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=gnu11 -O0 -g -include config.h -pthread -MD -MQ dfuzzer.p/src_rand.c.o -MF dfuzzer.p/src_rand.c.o.d -o dfuzzer.p/src_rand.c.o -c ../src/rand.c
../src/rand.c:541:17: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
                "%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n",
                ^
../src/rand.c:540:17: note: place parentheses around the string literal to silence warning
                "%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n" \
                ^
1 error generated.
```

**Comment by mrc0mmand** [comment]
> Turns out clang isn't happy :-)
> 
> ```shell
> FAILED: dfuzzer.p/src_rand.c.o 
> clang -Idfuzzer.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=gnu11 -O0 -g -include config.h -pthread -MD -MQ dfuzzer.p/src_rand.c.o -MF dfuzzer.p/src_rand.c.o.d -o dfuzzer.p/src_rand.c.o -c ../src/rand.c
> ../src/rand.c:541:17: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
>                 "%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n",
>                 ^
> ../src/rand.c:540:17: note: place parentheses around the string literal to silence warning
>                 "%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n" \
>                 ^
> 1 error generated.
> ```

Oh well. That warning was introduced in clang-12, and the build CI jobs was, unfortunately, stuck with clang-10, so it slipped by. Both the warning and the old CI images should be, hopefully, addressed by https://github.com/dbus-fuzzer/dfuzzer/pull/135.

**Pull request merged**
