### PR TITLE
meson: use version tag generated by meson

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@evverx I have a spec file change ready for Rawhide, so maybe after merging this I could do a PR which drops all the Makefile stuff (where Packit will inevitably fail), merge that, tag v2.0, push the Rawhide change, and then check if everything still works as expected

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

What's weird is that `G_STRINGIFY(DFUZZER_VERSION)` is somehow compatible with `Makefile` in the sense that it somehow turns into `DFUZZER_VERSION`

**Comment by evverx** [comment]
> maybe after merging this I could do a PR which drops all the Makefile stuff (where Packit will inevitably fail), merge that, tag v2.0, push the Rawhide change, and then check if everything still works as expected

Sounds good to me

**Comment by mrc0mmand** [comment]
> LGTM. Thanks!
> 
> What's weird is that `G_STRINGIFY(DFUZZER_VERSION)` is somehow compatible with `Makefile` in the sense that it somehow turns into `DFUZZER_VERSION`

I was surprised as well, but it makes sense given how the G_STRIGIFY() stuff is implemented:

```c
#include <stdio.h>

#define I_EXIST hello
#define XSTRINGIFY(x) #x
#define STRINGIFY(x) XSTRINGIFY(x)


int main(void) {
    printf("%s\n", STRINGIFY(I_DONT_EXIST));
    printf("%s\n", STRINGIFY(I_EXIST));

    return 0;
}
```

```
$ ./test 
I_DONT_EXIST
hello
```

**Pull request merged**
